env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    gitlab_token: "ENCRYPTED[!82b4a7234f86c63ebdba0c1c72728f26224d7ee1c83935fdb755d84108459c8dcd66df7154d34a0229a0af88bb8d3455!]"
    github_token: "ENCRYPTED[!82ee7e07446c86fe97dda507543443a525fec83e693679c8f84d740764987310d74262013f45a1e5a56cc54e334e8f7c!]"
    bot_api: "ENCRYPTED[!10482e25ca82cf0efa74e4c474a9e5cb82c1b2e5545657dd1917cba34aa08ce880b37bef99a47d0a49c4bb48523144b9!]"
    chat_id: "ENCRYPTED[!c519abe30864df229179faa4e1eeaa0fde992d896ed620d45cb1f2ca25f0ee3b9373d08fb64a737c8759ae592ef9351c!]"

# store information about repo , username and gmail here
    device_codename: lavender
    gmail: SpiDy2713@gmail.com
    github_username: ImSpiDy
    gitlab_username: ImSpiDy
    gitlab_reponame: cirrus-cache
    github_reponame: cirrus-script
    rom_name: nusa

# store build information
    lunch: "nad_lavender-userdebug"
    compile_plox: "make nad -j$(nproc --all)"

task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_ccache_script: # Upload ccache to cloud foreground
      - bash upload_ccache # Ccache uploading script
